spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_castle
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: crm
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    default-schema: crm
    schemas: crm

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: info
